zellij - prevent infinite session opening with same name

diff --git a/zsh/zlogin b/zsh/zlogin
--- a/zsh/zlogin
+++ b/zsh/zlogin
@@ -15,8 +15,11 @@ if is_zsh_interactive && test "${TERM}" != 'dumb' && test -n "${SSH_TTY}"; then
   test -z "${DISPLAY}" && export DISPLAY=:20 # it's required to run ssh like `ssh -R 6020:/tmp/.X11-unix/X0 [host]`
   # or `RemoteForward 6020 /tmp/.X11-unix/X0` in ~/.ssh/config
 
-  echo 'Attempting to attach to zellij session and this might fail as zellij might be not stable'
-  UNSET_ALL_MY_ZSH_STUFF_LOADED=1 exec-zellij-attach ssh
+  # prevent infinite session opening with the same name, 'ssh'
+  zellij list-sessions | grep ssh | xargs test ssh = || {
+    echo 'Attempting to attach to zellij session and this might fail as zellij might be not stable'
+    UNSET_ALL_MY_ZSH_STUFF_LOADED=1 exec-zellij-attach ssh
+  }
 fi
 
 # to mimic secretive experience at macOS on WSL
