zsh - shield employing zellij under tmux

diff --git a/zsh/zlogin b/zsh/zlogin
--- a/zsh/zlogin
+++ b/zsh/zlogin
@@ -15,20 +15,23 @@ if is_zsh_interactive && test "${TERM}" != 'dumb' && test -n "${SSH_TTY}"; then
   test -z "${DISPLAY}" && export DISPLAY=:20 # it's required to run ssh like `ssh -R 6020:/tmp/.X11-unix/X0 [host]`
   # or `RemoteForward 6020 /tmp/.X11-unix/X0` in ~/.ssh/config
 
-  # prevent infinite session opening with the same name, 'ssh'
-  zellij list-sessions \
-    | grep ssh | head -n1 | sed 's/ (current)$//' \
-    | grep -E '^ssh$' > /dev/null \
-    && {
-    echo 'an existing ssh session is found as below'
-    zellij list-sessions
-    echo 'attaching to zellij is being skipped to avoid potential nested sessions'
-    echo 'you can still attach via `zellij attach ssh`...'
-    sleep 3
-  } || {
-    echo 'Attempting to attach to zellij session and this might fail as zellij might be not stable'
-    UNSET_ALL_MY_ZSH_STUFF_LOADED=1 exec-zellij-attach ssh
-  }
+  # consider opening `zellij` only if not running under `tmux` already
+  if ! printenv TMUX > /dev/null; then
+    # prevent infinite session opening with the same name, 'ssh'
+    zellij list-sessions \
+      | grep ssh | head -n1 | sed 's/ (current)$//' \
+      | grep -E '^ssh$' > /dev/null \
+      && {
+        echo 'an existing ssh session is found as below'
+        zellij list-sessions
+        echo 'attaching to zellij is being skipped to avoid potential nested sessions'
+        echo 'you can still attach via `zellij attach ssh`...'
+        sleep 3
+      } || {
+        echo 'Attempting to attach to zellij session and this might fail as zellij might be not stable'
+        UNSET_ALL_MY_ZSH_STUFF_LOADED=1 exec-zellij-attach ssh
+      }
+  fi
 fi
 
 # to mimic secretive experience at macOS on WSL
